set_false_path -from [get_clocks clk_out1_pl_system_clk_wiz_0] -to [get_clocks clk_out2_pl_system_clk_wiz_0]
set_property OFFCHIP_TERM NONE [get_ports HBM_CATTRIP]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
